### ISSUE TITLE
Support Enum Type

### ISSUE THREAD

**Issue by xiamx** [SweetIQ/schemats#15]
Add support for Postgres Enum Type https://www.postgresql.org/docs/current/static/datatype-enum.html

**Comment by jmealo** [comment]
This snippet may be helpful:

```
SELECT pg_type.typname AS type,
       pg_type.oid AS oid,
       pg_namespace.nspname AS schema,
       (
         SELECT json_agg(pg_enum.enumlabel)
           FROM pg_enum
          WHERE pg_enum.enumtypid = pg_type.oid
       ) AS allowed_values
  FROM pg_type
  JOIN pg_namespace ON pg_namespace.oid = pg_type.typnamespace
 WHERE pg_type.typtype = 'e'
```

The subquery avoids a hash join and appears to be faster on 50 or so enums. I did not test extensively.

```sql
  SELECT pg_type.typname AS type,
         pg_type.oid AS oid,
         pg_namespace.nspname AS schema,
         json_agg(pg_enum.enumlabel) AS allowed_values
    FROM pg_type
    JOIN pg_enum
      ON pg_enum.enumtypid = pg_type.oid
    JOIN pg_namespace ON pg_namespace.oid = pg_type.typnamespace
GROUP BY pg_namespace.nspname, pg_type.typname, pg_type.oid;
```

We should be able safely disregard ordering by `enumsortorder` for our purposes.

**Comment by xiamx** [comment]
@jmealo thanks for the input. I have a work in progress of the implementation in [enumtype](https://github.com/SweetIQ/schemats/tree/enumtype) branch. Currently on hold because https://github.com/SweetIQ/schemats/pull/14 refactored some low level functions to support schema/tablennamespaces. It will be best to have #14 merged first.

**Comment by xiamx** [comment]
Looks like there's a working implementation in this fork https://github.com/gust/schemats .
