### ISSUE TITLE
Maybe project can be merged with https://github.com/typeorm/typeorm

### ISSUE THREAD

**Issue by born2net** [SweetIQ/schemats#16]
Maybe project can be merged with https://github.com/typeorm/typeorm
combined efforts,

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by born2net** [comment]
reg: https://github.com/typeorm/typeorm/issues/124#issuecomment-266482601

**Comment by xiamx** [comment]
Hi, 

I agree with @pleerock . schemats and typeorm have different opinions on interacting with databases. We may be able to share some common modules but the general directions don't converge.

**Comment by born2net** [comment]
ok np
