### ISSUE TITLE
Support numeric type

### ISSUE THREAD

**Issue by abenhamdine** [SweetIQ/schemats#20]
I just started to use this module, but unfortunately, only a few types seem to be mapped : 
```
TypeError: do not know how to convert type [numeric]
```

Would it be possible to add numeric type mapping ?

Thx by advance.

**Comment by xiamx** [comment]
This can be supported by adding a line `case 'numeric':` on the type mapping function https://github.com/SweetIQ/schemats/blob/master/src/schema.ts#L54

Other types can also be supported by adding respective mappings.

Pull requests are welcomed 👍

**Comment by abenhamdine** [comment]
Yes, thx ! I eventually found the relevant code too.
Ok, I will send a PR in order to add some frequent datatypes in the upcoming days, I'm glad to help on this.
