### ISSUE TITLE
Camelized column names

### ISSUE THREAD

**Issue by vitaly-t** [SweetIQ/schemats#22]
In case you want automatically camelized column names, see event [receive](http://vitaly-t.github.io/pg-promise/global.html#event:receive), and the example that follows :wink: Could make for a nicer TypeScript style :wink:

Caramelized, LOL 😸

**Comment by abenhamdine** [comment]
+1 for the feature : as a fresh user of this module, I was precisely thinking about this.
But I wonder : why use pgp event receive, and not camelize while generating ts code in https://github.com/SweetIQ/schemats/blob/master/src/typescript.ts#L16 ?

**Comment by xiamx** [comment]
Yup, this is definitely needed.  We guys at SweetIQ didn't experience this _camel_snakeCase_ _eye candy_ because our database was migrated from a mongodb database where keys(columns) are all camelCased :joy: . But we instead had to double quote all column names in our SQL queries.
