### ISSUE TITLE
Support more data types

### ISSUE THREAD

**Issue by abenhamdine** [SweetIQ/schemats#24]
I open this issue just for the record : in PR https://github.com/SweetIQ/schemats/pull/21, I didn't add all sql types, since there so many, and I think the mapping still lacks some common ones : 
- inet type
- timestamptz

If I a had some time, I will submit a PR for this.

If anyone would suggest more types to add ?

**Comment by abenhamdine** [comment]
I realize that it lacks also : 
- char
- jsonb
- time
- float4

**Comment by xiamx** [comment]
@elizabethkilson 's fork gust/schemats includes [some more type mappings](https://github.com/SweetIQ/schemats/commit/f8927e682f4347fd34855e95ef93a8def813567d). They also seem to have a working enum type support proposed in #15 .

**Comment by abenhamdine** [comment]
Looks like there's a risk of merge conflict beetween a potention PR on this, and a future merge of gust enum implementation.

However if it's ok for you, I will first submit a PR with all additionnal types (those in gust/schemats fork will be covered in the PR too).

**Comment by xiamx** [comment]
#28 for record

**Comment by abenhamdine** [comment]
Closed since #28 has been merged
