### ISSUE TITLE
Schemats generates empty file

### ISSUE THREAD

**Issue by umer4ik** [SweetIQ/schemats#57]
My env: Windows x64, MySQL 5.5
I try cli with command
`schemats generate -c mysql://root:1@localhost/db -t users -o db.ts`
and the output file content is 
```
export namespace usersFields {

}

export interface users {

}
```
Database has table users with data, what am I doing wrong?

**Comment by xiamx** [comment]
@crispmark Can you take a look at this one?

**Comment by crispmark** [comment]
Hi @umer4ik, try
```
schemats generate -c mysql://root:1@localhost/db -s db -t users -o db.ts
```

**Comment by umer4ik** [comment]
@crispmark works good, thanks a lot!
