### ISSUE TITLE
Improve the header details

### ISSUE THREAD

**Issue by vitaly-t** [SweetIQ/schemats#73]
This is a feature request for this code: https://github.com/SweetIQ/schemats/blob/master/src/index.ts#L37

Any typical header like this is expected to include the library's name + exact version that was used for generating the file, so you know when it is worthwhile regenerating it, and which tool to use for it, if newer versions are available. Just providing Date/Time doesn't give enough information.

Here's an example I used within pg-promise:

```js
/////////////////////////////////////////////////////////////////////////
// This file was automatically generated by pg-promise v.4.3.8
//
// Generated on: 6/2/2016, at 2:15:23 PM
// Total files: 15
//
// API: http://vitaly-t.github.io/pg-promise/utils.html#.buildSqlModule
/////////////////////////////////////////////////////////////////////////
```

The version should be injected as the value from `require('./package.json').version`.

**Comment by xiamx** [comment]
Implemented 🎉
